App\Entity\Location:
  properties:
    city:
      - NotBlank:
          groups: ['create', 'edit']
      - Length:
          min: 3
          groups: [ 'create', 'edit' ]
    country:
      - NotBlank:
          groups: ['create', 'edit']
      - Length:
          min: 2
          max: 2
          groups: ['create', 'edit']
    longitude:
      - NotBlank:
          groups: [ 'create', 'edit' ]
      - Range:
          min: -180
          max: 179
          groups: ['create', 'edit']
    latitude:
      - Range:
          min: -90
          max: 90
          groups: [ 'create', 'edit' ]

App\Entity\Forecast:
  properties:
    date:
      - NotBlank:
          groups: ['create', 'edit']
    temperature:
      - NotBlank:
          groups: ['create', 'edit']
      - Range:
          min: -50
          max: 50
          groups: ['create', 'edit']
    atmospheric_pressure:
      - NotBlank:
          groups: [ 'create', 'edit' ]
      - Range:
          min: 800
          max: 1100
          groups: [ 'create', 'edit' ]